### ISSUE TITLE
probleme de stockage de la conso electrique 

### ISSUE THREAD

**Issue by fbell58** [AgP42/suiviCO2#2]
Bonjour

je me suis rendu compte que la consommation EDF indiquée par le plugin est differente de celle de mon linky …

Apres quelques recherche je pense avoir trouvé
j ai remarqué qu il me manque des informations de sonsomation certaines heures (en regardant dans la table history …)
J ai creusé un peu plus et je pense avoir trouvé je voudrais savoir si qq a le même soucis et confirmer mon analyse et en faire profiter les autres si j ai raison bien sur

voila la partie qui stocke la conso en base
**> ***
> //si cette consommation est >0, on va la stocker en base - NON, il faut stocker les 0 sinon l’archivage de l’historique fait n’importe quoi… dommage de stocker des 0…
> * // TODO a ameliorer…
> ***
> * if ($consumption < 1000) { //1000 kWh c’est environ 170€, si on consomme ca par heure c’est qu’on a un gros probleme… Ce test permet de ne pas sauvegarder l’index entier lors de la 1ere boucle apres la creation de l’objet.
> * $cmd = $this->getCmd(null, ‹ consumption › . $_type);
> * if (is_object($cmd)) {
> * $cmd->setCollectDate($datetime);
> * log::add(‹ suiviCO2 ›, ‹ debug ›, 'eqLogic_id : ’ . $this->getId() . ’ - Index now ’ . $_type . ’ : ’ . $index . ’ - Prev Index ’ . $_type . ’ : ’ . $lastValue . ’ = conso ’ . $_type . ’ (Wh) : ’ . $consumption);
> * $cmd->event($consumption);*
> * }*
> * }***

hors la conso est stockée en WH et pas en KWh (ligne precedente **$consumption = $consumption*$coef_thermique;**) du coup quand mon ballon eau chaude démarre (heure creuse) il consomme 3000 WH et n est pas enregistré …il faut test > 1000000 et pas 1000 …

qu en penser vous

**Comment by AgP42** [comment]
Corrigé !
