### ISSUE TITLE
API obsolète

### ISSUE THREAD

**Issue by Fardenco** [AgP42/suiviCO2#5]
Bonjour, j'ai essayé d'installer le plugin mais aucune donnée ne remonte concernant le co2/kWh. J'ai fouillé un peu, et il semblerait que l'API utilisée soit obsolète.
En faisant un appel à la main sur https://opendata.reseaux-energies.fr/api/records/1.0/search/?dataset=eco2mix-national-tr&rows=5&sort=date_heure on peut voir qu'on a bien un retour mais que les résultats ne contiennent pas de champ "taux_co2".
Je pense qu'il suffirait de remplacer l'API par sa dernière version.
https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/eco2mix-national-tr/records?limit=5&order_by=date_heure DESC&where=taux_co2>0
J'ai dû rajouter la condition where=taux_co2>0 car sans ça l'API renvoie des résultats avec une date future qui ne contiennent rien.
En dehors de ça la structure du json a un peu changé avec la dernière version de l'API.
Peut-être que ça serait aussi intéressant d'exposer les champs qui indiquent d'où provient l'énergie afin qu'on puisse en faire ce qu'on veut dans Jeedom, mais ça c'est vraiment du bonus.
Merci pour ton travail en tous cas.
Edit : J'ai proposé une modification du code qui devrait résoudre le problème.

**Comment by AgP42** [comment]
hello, 

désolé, je n'avais pas vu cette proposition de pull request, dont je te remercie. 
Superbricolo a posté aujourd'hui un autre pull request, qui devrait semble-t-il couvrir aussi les modifs que tu as proposées, je rejete donc ce pull request !
Je vais aussi t'ajouter comme contributeur au projet pour l'avenir si tu veux le faire évoluer et le maintenir, ce que je n'ai plus le temps de faire, notamment parce que je n'ai plus aucun jeedom actif.
